// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnN53YjIj_ssN3mgvdYFz5h-k2AmLC-u0',
    appId: '1:870444676197:web:61e7303b4f503730d9428c',
    messagingSenderId: '870444676197',
    projectId: 'bank-e5f53',
    authDomain: 'bank-e5f53.firebaseapp.com',
    storageBucket: 'bank-e5f53.appspot.com',
    measurementId: 'G-0ETX8QWMW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ccoyxLkLyTHVJPIVFl6VletKLzPjmuc',
    appId: '1:870444676197:android:69f8c423be569e23d9428c',
    messagingSenderId: '870444676197',
    projectId: 'bank-e5f53',
    storageBucket: 'bank-e5f53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGRZnuxXQqmrRi6UJ1QCY3krubMYV1o1c',
    appId: '1:870444676197:ios:0080fae5d55b08fed9428c',
    messagingSenderId: '870444676197',
    projectId: 'bank-e5f53',
    storageBucket: 'bank-e5f53.appspot.com',
    iosClientId: '870444676197-67m2l78it3eet057emef4tbheqc95upm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bank2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGRZnuxXQqmrRi6UJ1QCY3krubMYV1o1c',
    appId: '1:870444676197:ios:0080fae5d55b08fed9428c',
    messagingSenderId: '870444676197',
    projectId: 'bank-e5f53',
    storageBucket: 'bank-e5f53.appspot.com',
    iosClientId: '870444676197-67m2l78it3eet057emef4tbheqc95upm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bank2',
  );
}
